/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.okaynet.andare.gui;

import br.com.okaynet.andare.bibliotecas.Util;
import br.com.okaynet.andare.conexao.Data;
import br.com.okaynet.andare.conexao.TransactionManager;
import br.com.okaynet.andare.daos.DaoClienteFisico;
import br.com.okaynet.andare.daos.DaoClienteJuridico;
import br.com.okaynet.andare.daos.DaoFuncionario;
import br.com.okaynet.andare.daos.DaoOrdemServico;
import br.com.okaynet.andare.model.ClienteFisico;
import br.com.okaynet.andare.model.ClienteJuridico;
import br.com.okaynet.andare.model.Endereco;
import br.com.okaynet.andare.model.Funcionario;
import br.com.okaynet.andare.model.OrdemServico;
import br.com.okaynet.andare.model.Pessoa;
import br.com.okaynet.andare.model.Usuarios;
import br.com.okaynet.andare.bibliotecas.Extenso;
import br.com.okaynet.andare.bibliotecas.ReportManage;
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Erick
 */
public class JDialogCadastroOrdem extends javax.swing.JDialog {

    /**
     * Creates new form JDialogCadastroCliente
     */
    public JDialogCadastroOrdem(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        popularComboFuncionario();
        popularComboCliente();
        preencherEndereco();
        modificarEndereco();
        iniciarPreencher();
        iniciarThreadCalculoValor();
        iniciarThreadQtdeCarateres();
        novo();
        Usuarios autenticado = (Usuarios) Data.hash.get("usuario");


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldDataCadastro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldEndereco = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxTipoLogradouro = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldBairro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBoxCidade = new javax.swing.JComboBox();
        jComboBoxStatus = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxCliente = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jCheckBoxEndereco = new javax.swing.JCheckBox();
        jFormattedTextFieldDataVencimento = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNumero = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        jFormattedTextFieldValorPar = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextFieldJuros = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jComboBoxFuncionarios = new javax.swing.JComboBox();
        jTextFieldValor = new javax.swing.JTextField();
        jComboBoxQuantParcelas = new javax.swing.JComboBox();
        jComboBoxParcelasRest = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldItem1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldValor1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldItem2 = new javax.swing.JTextField();
        jTextFieldValor2 = new javax.swing.JTextField();
        jTextFieldValor3 = new javax.swing.JTextField();
        jTextFieldItem3 = new javax.swing.JTextField();
        jTextFieldValor4 = new javax.swing.JTextField();
        jTextFieldItem4 = new javax.swing.JTextField();
        jLabelItem4 = new javax.swing.JLabel();
        jLabelItem1 = new javax.swing.JLabel();
        jLabelItem2 = new javax.swing.JLabel();
        jLabelItem3 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxStatusServico = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        jTextFieldEquipamento = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldDeslocamento = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextFieldModelo = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextFieldSerie = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaProblema = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAcessorios = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de OS");
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(905, 687));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(905, 687));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel1.setText("Data Cadastro* :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jTextFieldDataCadastro.setEditable(false);
        getContentPane().add(jTextFieldDataCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 100, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("Data Vencimento* :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel4.setText("Status* :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel8.setText("Valor* ##.# :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 10));

        jTextFieldEndereco.setEditable(false);
        getContentPane().add(jTextFieldEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 370, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel9.setText("Endereço* :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jComboBoxTipoLogradouro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rua", "Avenida" }));
        getContentPane().add(jComboBoxTipoLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel10.setText("Numero* :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, -1, -1));

        jTextFieldComplemento.setEditable(false);
        getContentPane().add(jTextFieldComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 170, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel12.setText("CEP* :");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, -1, -1));

        jTextFieldBairro.setEditable(false);
        getContentPane().add(jTextFieldBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 130, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel13.setText("Bairro* :");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel14.setText("Cidade* :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        jComboBoxCidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Abatiá", "Adrianópolis", "Agudos do Sul", "Almirante Tamandaré", "Altamira do Paraná", "Alto Paraíso", "Alto Paraná", "Alto Piquiri", "Altônia", "Alvorada do Sul", "Amaporã", "Ampére", "Anahy", "Andirá", "Ângulo", "Antonina", "Antônio Olinto", "Apucarana", "Arapongas", "Arapoti", "Arapuã", "Araruna", "Araucária", "Ariranha do Ivaí", "Assaí", "Assis Chateaubriand", "Astorga", "Atalaia", "Balsa Nova", "Bandeirantes", "Barbosa Ferraz", "Barra do Jacaré", "Barracão", "Bela Vista da Caroba", "Bela Vista do Paraíso", "Bituruna", "Boa Esperança", "Boa Esperança do Iguaçu", "Boa Ventura de São Roque", "Boa Vista da Aparecida", "Bocaiuva do Sul", "Bom Jesus do Sul", "Bom Sucesso", "Bom Sucesso do Sul", "Borrazópolis", "Braganey", "Brasilândia do Sul", "Cafeara", "Cafelândia", "Cafezal do Sul", "Califórnia", "Cambará", "Cambé", "Cambira", "Campina da Lagoa", "Campina do Simão", "Campina Grande do Sul", "Campo Bonito", "Campo do Tenente", "Campo Largo", "Campo Magro", "Campo Mourão", "Cândido de Abreu", "Candói", "Cantagalo", "Capanema", "Capitão Leônidas Marques", "Carambeí", "Carlópolis", "Cascavel", "Castro", "Catanduvas", "Centenário do Sul", "Cerro Azul", "Céu Azul", "Chopinzinho", "Cianorte", "Cidade Gaúcha", "Clevelândia", "Colombo", "Colorado", "Congonhinhas", "Conselheiro Mairinck", "Contenda", "Corbélia", "Cornélio Procópio", "Coronel Domingos Soares", "Coronel Vivida", "Corumbataí do Sul", "Cruz Machado", "Cruzeiro do Iguaçu", "Cruzeiro do Oeste", "Cruzeiro do Sul", "Cruzmaltina", "Curitiba", "Curiúva", "Diamante do Norte", "Diamante do Sul", "Diamante d'Oeste", "Dois Vizinhos", "Douradina", "Doutor Camargo", "Doutor Ulysses", "Enéas Marques", "Engenheiro Beltrão", "Entre Rios do Oeste", "Esperança Nova", "Espigão Alto do Iguaçu", "Farol", "Faxinal", "Fazenda Rio Grande", "Fênix", "Fernandes Pinheiro", "Figueira", "Flor da Serra do Sul", "Floraí", "Floresta", "Florestópolis", "Flórida", "Formosa do Oeste", "Foz do Iguaçu", "Foz do Jordão", "Francisco Alves", "Francisco Beltrão", "General Carneiro", "Godoy Moreira", "Goioerê", "Goioxim", "Grandes Rios", "Guaíra", "Guairaçá", "Guamiranga", "Guapirama", "Guaporema", "Guaraci", "Guaraniaçu", "Guarapuava", "Guaraqueçaba", "Guaratuba", "Honório Serpa", "Ibaiti", "Ibema", "Ibiporã", "Icaraíma", "Iguaraçu", "Iguatu", "Imbaú", "Imbituva", "Inácio Martins", "Inajá", "Indianópolis", "Ipiranga", "Iporã", "Iracema do Oeste", "Irati", "Iretama", "Itaguajé", "Itaipulândia", "Itambaracá", "Itambé", "Itapejara d'Oeste", "Itaperuçu", "Itaúna do Sul", "Ivaí", "Ivaiporã", "Ivaté", "Ivatuba", "Jaboti", "Jacarezinho", "Jaguapitã", "Jaguariaíva", "Jandaia do Sul", "Janiópolis", "Japira", "Japurá", "Jardim Alegre", "Jardim Olinda", "Jataizinho", "Jesuítas", "Joaquim Távora", "Jundiaí do Sul", "Juranda", "Jussara", "Kaloré", "Lapa", "Laranjal", "Laranjeiras do Sul", "Leópolis", "Lidianópolis", "Lindoeste", "Loanda", "Lobato", "Londrina", "Luiziana", "Lunardelli", "Lupionópolis", "Mallet", "Mamborê", "Mandaguaçu", "Mandaguari", "Mandirituba", "Manfrinópolis", "Mangueirinha", "Manoel Ribas", "Marechal Cândido Rondon", "Maria Helena", "Marialva", "Marilândia do Sul", "Marilena", "Mariluz", "Maringá", "Mariópolis", "Maripá", "Marmeleiro", "Marquinho", "Marumbi", "Matelândia", "Matinhos", "Mato Rico", "Mauá da Serra", "Medianeira", "Mercedes", "Mirador", "Miraselva", "Missal", "Moreira Sales", "Morretes", "Munhoz de Melo", "Nossa Senhora das Graças", "Nova Aliança do Ivaí", "Nova América da Colina", "Nova Aurora", "Nova Cantu", "Nova Esperança", "Nova Esperança do Sudoeste", "Nova Fátima", "Nova Laranjeiras", "Nova Londrina", "Nova Olímpia", "Nova Prata do Iguaçu", "Nova Santa Bárbara", "Nova Santa Rosa", "Nova Tebas", "Novo Itacolomi", "Ortigueira", "Ourizona", "Ouro Verde do Oeste", "Paiçandu", "Palmas", "Palmeira", "Palmital", "Palotina", "Paraíso do Norte", "Paranacity", "Paranaguá", "Paranapoema", "Paranavaí", "Pato Bragado", "Pato Branco", "Paula Freitas", "Paulo Frontin", "Peabiru", "Perobal", "Pérola", "Pérola d'Oeste", "Piên", "Pinhais", "Pinhal de São Bento", "Pinhalão", "Pinhão", "Piraí do Sul", "Pitanga", "Pitangueiras", "Planaltina do Paraná", "Planalto", "Ponta Grossa", "Pontal do Paraná", "Porecatu", "Porto Amazonas", "Porto Barreiro", "Porto Rico", "Porto Vitória", "Prado Ferreira", "Pranchita", "Presidente Castelo Branco", "Primeiro de Maio", "Prudentópolis", "Prudentópolis", "Quarto Centenário", "Quatiguá", "Quatro Barras", "Quatro Pontes", "Quedas do Iguaçu", "Querência do Norte", "Quinta do Sol", "Quitandinha", "Ramilândia", "Rancho Alegre", "Rancho Alegre d'Oeste", "Realeza", "Rebouças", "Renascença", "Reserva", "Reserva do Iguaçu", "Ribeirão Claro", "Ribeirão do Pinhal", "Rio Azul", "Rio Bom", "Rio Bonito do Iguaçu", "Rio Branco do Ivaí", "Rio Branco do Sul", "Rio Negro", "Rolândia", "Roncador", "Rondon", "Rosário do Ivaí", "Sabáudia", "Salgado Filho", "Salto do Itararé", "Salto do Lontra", "Santa Amélia", "Santa Cecília do Pavão", "Santa Cruz de Monte Castelo", "Santa Fé", "Santa Helena", "Santa Inês", "Santa Isabel do Ivaí", "Santa Izabel do Oeste", "Santa Lúcia", "Santa Maria do Oeste", "Santa Mariana", "Santa Mônica", "Santa Tereza do Oeste", "Santa Terezinha de Itaipu", "Santana do Itararé", "Santo Antônio da Platina", "Santo Antônio do Caiuá", "Santo Antônio do Paraíso", "Santo Antônio do Sudoeste", "Santo Inácio", "São Carlos do Ivaí", "São Jerônimo da Serra", "São João", "São João do Caiuá", "São João do Ivaí", "São João do Triunfo", "São Jorge do Ivaí", "São Jorge do Patrocínio", "São Jorge d'Oeste", "São José da Boa Vista", "São José das Palmeiras", "São José dos Pinhais", "São Manoel do Paraná", "São Mateus do Sul", "São Miguel do Iguaçu", "São Pedro do Iguaçu", "São Pedro do Ivaí", "São Pedro do Paraná", "São Sebastião da Amoreira", "São Tomé", "Sapopema", "Sarandi", "Saudade do Iguaçu", "Sengés", "Serranópolis do Iguaçu", "Sertaneja", "Sertanópolis", "Siqueira Campos", "Sulina", "Tamarana", "Tamboara", "Tapejara", "Tapira", "Teixeira Soares", "Telêmaco Borba", "Terra Boa", "Terra Rica", "Terra Roxa", "Tibagi", "Tijucas do Sul", "Toledo", "Tomazina", "Três Barras do Paraná", "Tunas do Paraná", "Tuneiras do Oeste", "Tupãssi", "Turvo", "Ubiratã", "Umuarama", "União da Vitória", "Uniflor", "Uraí", "Ventania", "Vera Cruz do Oeste", "Verê", "Virmond", "Vitorino", "Wenceslau Braz", "Xambrê" }));
        getContentPane().add(jComboBoxCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 190, -1));

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aguardando Pagamento", "Pagamento Concluido", "Pagamento em Cheque" }));
        jComboBoxStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusActionPerformed(evt);
            }
        });
        jComboBoxStatus.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxStatusPropertyChange(evt);
            }
        });
        getContentPane().add(jComboBoxStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 190, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel20.setText("Funcionario* :");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        jComboBoxCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxClienteActionPerformed(evt);
            }
        });
        jComboBoxCliente.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxClientePropertyChange(evt);
            }
        });
        getContentPane().add(jComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 220, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel21.setText("Cliente* :");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel22.setText("Qnt. Parc:");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, 10));

        jCheckBoxEndereco.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jCheckBoxEndereco.setForeground(new java.awt.Color(204, 0, 0));
        jCheckBoxEndereco.setSelected(true);
        jCheckBoxEndereco.setText("O Endereço de cobrança é o mesmo endereço do Cliente selecionado");
        jCheckBoxEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBoxEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));

        try {
            jFormattedTextFieldDataVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldDataVencimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 100, -1));

        jFormattedTextFieldNumero.setEditable(false);
        jFormattedTextFieldNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(jFormattedTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 60, -1));

        jFormattedTextFieldCep.setEditable(false);
        try {
            jFormattedTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 350, 160, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel23.setText("Juros % ao dia:");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 80, 10));

        jFormattedTextFieldValorPar.setEditable(false);
        jFormattedTextFieldValorPar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        getContentPane().add(jFormattedTextFieldValorPar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 60, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel24.setText("Parc. Rest:");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 10));

        jTextFieldJuros.setText("0");
        jTextFieldJuros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJurosActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldJuros, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 70, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel25.setText("Valor Parc:");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 50, 10));

        getContentPane().add(jComboBoxFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, 210, -1));

        jTextFieldValor.setEditable(false);
        jTextFieldValor.setText("0.0");
        jTextFieldValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 70, -1));

        jComboBoxQuantParcelas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(jComboBoxQuantParcelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 50, -1));

        jComboBoxParcelasRest.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        getContentPane().add(jComboBoxParcelasRest, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 50, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Serviços"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldItem1.setMaximumSize(new java.awt.Dimension(370, 2147483647));
        jTextFieldItem1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldItem1FocusGained(evt);
            }
        });
        jPanel1.add(jTextFieldItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 43, 680, -1));

        jLabel5.setText("Itens:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 23, -1, -1));

        jTextFieldValor1.setText("0.0");
        jPanel1.add(jTextFieldValor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 114, -1));

        jLabel6.setText("Valores R$:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));
        jPanel1.add(jTextFieldItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 74, 680, -1));

        jTextFieldValor2.setText("0.0");
        jPanel1.add(jTextFieldValor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 70, 114, -1));

        jTextFieldValor3.setText("0.0");
        jPanel1.add(jTextFieldValor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 114, -1));
        jPanel1.add(jTextFieldItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 105, 680, -1));

        jTextFieldValor4.setText("0.0");
        jPanel1.add(jTextFieldValor4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 114, -1));
        jPanel1.add(jTextFieldItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 136, 680, -1));

        jLabelItem4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelItem4.setForeground(new java.awt.Color(0, 153, 0));
        jLabelItem4.setText("0");
        jPanel1.add(jLabelItem4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, -1, -1));

        jLabelItem1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelItem1.setForeground(new java.awt.Color(0, 153, 0));
        jLabelItem1.setText("0");
        jPanel1.add(jLabelItem1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 50, -1, -1));

        jLabelItem2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelItem2.setForeground(new java.awt.Color(0, 153, 0));
        jLabelItem2.setText("0");
        jPanel1.add(jLabelItem2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, -1, -1));

        jLabelItem3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelItem3.setForeground(new java.awt.Color(0, 153, 0));
        jLabelItem3.setText("0");
        jPanel1.add(jLabelItem3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 860, 180));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel15.setText("Complemento* :");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, -1));

        jComboBoxStatusServico.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não iniciado", "Em andamento", "Concluido", "Concluido e entregue" }));
        jComboBoxStatusServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStatusServicoActionPerformed(evt);
            }
        });
        jComboBoxStatusServico.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jComboBoxStatusServicoPropertyChange(evt);
            }
        });
        getContentPane().add(jComboBoxStatusServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 200, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel28.setText("Status do serviço* :");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, -1, -1));

        jTextFieldEquipamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEquipamentoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldEquipamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 340, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel26.setText("Acessórios:");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 110, 10));

        jTextFieldDeslocamento.setText("0");
        jTextFieldDeslocamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDeslocamentoActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDeslocamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 70, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel27.setText("Deslocamento:");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 80, 10));

        jTextFieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModeloActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 210, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel29.setText("Modelo:");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 80, 10));

        jTextFieldMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, 120, -1));

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel30.setText("Marca:");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 130, 80, 10));

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel31.setText("Série:");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 130, 80, 10));

        jTextFieldSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSerieActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, 160, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel32.setText("Equipamento:");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 80, 10));

        jTextAreaProblema.setColumns(20);
        jTextAreaProblema.setRows(5);
        jScrollPane1.setViewportView(jTextAreaProblema);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 206, 630, 80));

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel33.setText("Problema informado:");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 110, 10));

        jTextAreaAcessorios.setColumns(20);
        jTextAreaAcessorios.setRows(5);
        jScrollPane2.setViewportView(jTextAreaAcessorios);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 206, 220, 80));

        jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 31));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(396, 31));

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/okaynet/andare/icons/png/001.png"))); // NOI18N
        jMenu2.setText("Novo");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/okaynet/andare/icons/png/111.png"))); // NOI18N
        jMenu4.setText("Pesquisar");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenu4.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu4MenuSelected(evt);
            }
        });
        jMenu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu4ActionPerformed(evt);
            }
        });
        jMenu4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jMenu4KeyReleased(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/okaynet/andare/icons/png/010.png"))); // NOI18N
        jMenu6.setText("Voltar");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/okaynet/andare/icons/png/006.png"))); // NOI18N
        jMenu1.setText("Salvar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenu4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4KeyReleased

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu4MenuSelected
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu4MenuSelected

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        if (jMenu4.isEnabled()) {
            this.setVisible(false);
            Util.abrirDialogCentralizado(new JDialogPesquisaOrdemMes(null, true));
            this.dispose();
        }
    }//GEN-LAST:event_jMenu4MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        if (Util.mostraMensagemEmTela("Deseja salvar?")) {
            salvar();
        }

    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        novo();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusActionPerformed

    }//GEN-LAST:event_jComboBoxStatusActionPerformed

    private void jComboBoxStatusPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxStatusPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxStatusPropertyChange

    private void jComboBoxClientePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxClientePropertyChange
    }//GEN-LAST:event_jComboBoxClientePropertyChange

    private void jComboBoxClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxClienteActionPerformed
        // TODO add your handling code here:
        preencherEndereco();
    }//GEN-LAST:event_jComboBoxClienteActionPerformed

    private void jCheckBoxEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEnderecoActionPerformed
        modificarEndereco();
    }//GEN-LAST:event_jCheckBoxEnderecoActionPerformed

    private void jTextFieldJurosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJurosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldJurosActionPerformed

    private void jTextFieldValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorActionPerformed

    private void jTextFieldItem1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldItem1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItem1FocusGained

    private void jComboBoxStatusServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusServicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusServicoActionPerformed

    private void jComboBoxStatusServicoPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jComboBoxStatusServicoPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusServicoPropertyChange

    private void jTextFieldEquipamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEquipamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEquipamentoActionPerformed

    private void jTextFieldDeslocamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDeslocamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDeslocamentoActionPerformed

    private void jTextFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModeloActionPerformed

    private void jTextFieldMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMarcaActionPerformed

    private void jTextFieldSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSerieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastroOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastroOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastroOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCadastroOrdem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCadastroOrdem dialog = new JDialogCadastroOrdem(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBoxEndereco;
    private javax.swing.JComboBox jComboBoxCidade;
    private javax.swing.JComboBox jComboBoxCliente;
    private javax.swing.JComboBox jComboBoxFuncionarios;
    private javax.swing.JComboBox jComboBoxParcelasRest;
    private javax.swing.JComboBox jComboBoxQuantParcelas;
    private javax.swing.JComboBox jComboBoxStatus;
    private javax.swing.JComboBox jComboBoxStatusServico;
    private javax.swing.JComboBox jComboBoxTipoLogradouro;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataVencimento;
    private javax.swing.JFormattedTextField jFormattedTextFieldNumero;
    private javax.swing.JFormattedTextField jFormattedTextFieldValorPar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelItem1;
    private javax.swing.JLabel jLabelItem2;
    private javax.swing.JLabel jLabelItem3;
    private javax.swing.JLabel jLabelItem4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextAreaAcessorios;
    private javax.swing.JTextArea jTextAreaProblema;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldDataCadastro;
    private javax.swing.JTextField jTextFieldDeslocamento;
    private javax.swing.JTextField jTextFieldEndereco;
    private javax.swing.JTextField jTextFieldEquipamento;
    private javax.swing.JTextField jTextFieldItem1;
    private javax.swing.JTextField jTextFieldItem2;
    private javax.swing.JTextField jTextFieldItem3;
    private javax.swing.JTextField jTextFieldItem4;
    private javax.swing.JTextField jTextFieldJuros;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldSerie;
    private javax.swing.JTextField jTextFieldValor;
    private javax.swing.JTextField jTextFieldValor1;
    private javax.swing.JTextField jTextFieldValor2;
    private javax.swing.JTextField jTextFieldValor3;
    private javax.swing.JTextField jTextFieldValor4;
    // End of variables declaration//GEN-END:variables

    private void novo() {

        jTextFieldItem1.setText(null);
        jTextFieldItem2.setText(null);
        jTextFieldItem3.setText(null);
        jTextFieldItem4.setText(null);
        jTextFieldValor1.setText(null);
        jTextFieldValor2.setText(null);
        jTextFieldValor3.setText(null);
        jTextFieldValor4.setText(null);
        jTextFieldBairro.setText(null);
        jTextFieldComplemento.setText(null);
        jTextFieldDataCadastro.setText(null);
        jTextFieldEndereco.setText(null);
        jTextFieldEquipamento.setText(null);
        jTextFieldModelo.setText(null);
        jTextFieldMarca.setText(null);
        jTextFieldSerie.setText(null);
        jTextAreaProblema.setText(null);
        jTextAreaAcessorios.setText(null);
        jComboBoxStatus.setSelectedIndex(0);
        jTextFieldJuros.setText("0");
        jTextFieldDeslocamento.setText("0");
        jFormattedTextFieldCep.setText(null);
        jFormattedTextFieldDataVencimento.setText(null);
        jFormattedTextFieldNumero.setText(null);
        jComboBoxQuantParcelas.setSelectedIndex(0);
        jComboBoxParcelasRest.setSelectedIndex(0);
        jComboBoxStatusServico.setSelectedIndex(0);
        jTextFieldValor.setText(null);
        jFormattedTextFieldValorPar.setText("0");
        jTextFieldDataCadastro.setText(Util.calendarToString(Calendar.getInstance()));
        preencherEndereco();

    }

    private void popularComboFuncionario() {
        TransactionManager.beginTransaction();
        List<Funcionario> fun = new DaoFuncionario().listar("", "nome");
        TransactionManager.commit();
        jComboBoxFuncionarios.removeAllItems();
        for (Funcionario funAgora : fun) {
            jComboBoxFuncionarios.addItem(funAgora);
        }
    }

    private void popularComboCliente() {
        List<Pessoa> pessoa = new ArrayList<Pessoa>();
        TransactionManager.beginTransaction();
        List<ClienteFisico> clientesF = new DaoClienteFisico().listar("", "nome");
        List<ClienteJuridico> clientesJ = new DaoClienteJuridico().listar("", "razaoSocial");
        TransactionManager.commit();

        for (ClienteJuridico clienteJuridico : clientesJ) {
            pessoa.add(clienteJuridico);
        }

        for (ClienteFisico clienteFisico : clientesF) {
            pessoa.add(clienteFisico);
        }

        jComboBoxCliente.removeAllItems();
        for (Pessoa funAgora : pessoa) {
            jComboBoxCliente.addItem(funAgora);
        }
    }

    private void salvar() {
        if (validaCamposEmBranco() && verificarQtdeDeCaracteresItens()) {
            OrdemServico ordem = new OrdemServico();
            ordem.setCliente((Pessoa) jComboBoxCliente.getSelectedItem());
            ordem.setDataCadastro(Util.stringToCalendar(jTextFieldDataCadastro.getText()));
            ordem.setDataVencimento(Util.stringToCalendar(jFormattedTextFieldDataVencimento.getText()));
            ordem.setItem1(jTextFieldItem1.getText());
            ordem.setEquipamento(jTextFieldEquipamento.getText());
            ordem.setModelo(jTextFieldModelo.getText());
            ordem.setMarca(jTextFieldMarca.getText());
            ordem.setAcessorio(jTextAreaAcessorios.getText());
            ordem.setSerie(jTextFieldSerie.getText());
            ordem.setProblemaInformado(jTextAreaProblema.getText());
            ordem.setItem2(jTextFieldItem2.getText());
            ordem.setItem3(jTextFieldItem3.getText());
            ordem.setItem4(jTextFieldItem4.getText());
            ordem.setFuncionario((Funcionario) jComboBoxFuncionarios.getSelectedItem());

            try {
                ordem.setParcelas(Integer.parseInt(jComboBoxQuantParcelas.getSelectedItem().toString()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Erro no numero de parcelas");
                return;
            }

            if (!jTextFieldDeslocamento.getText().isEmpty()) {
                try {
                    ordem.setDeslocamento(Double.parseDouble(jTextFieldDeslocamento.getText()));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Erro no campo de deslocamento, valor não confere. \n Verifique se você colocou virgulas e substitua por 'Ponto'");
                    return;
                }
            } else {
                ordem.setDeslocamento(0.0);
            }

            try {
                ordem.setParcelasRestantes(Integer.parseInt(jComboBoxParcelasRest.getSelectedItem().toString()));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Erro no total de parcelas restantes");
            }

            ordem.setStatus(jComboBoxStatus.getSelectedItem().toString());
            ordem.setStatusDoServivo(jComboBoxStatusServico.getSelectedItem().toString());

            if (!jTextFieldJuros.getText().isEmpty()) {
                try {
                    ordem.setJuros(Double.parseDouble(jTextFieldJuros.getText()));
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Erro no campo de juros, valor não confere. \n Verifique se você colocou virgulas e substitua por 'Ponto'");
                    return;
                }
            } else {
                ordem.setJuros(0.0);
            }
            Double valorTotal = 0.0;
            try {
                if (!jTextFieldValor1.getText().isEmpty()) {
                    ordem.setValor1(Double.parseDouble(jTextFieldValor1.getText()));
                } else {
                    //ordem.setValor1(0.0);
                }
                if (!jTextFieldValor2.getText().isEmpty()) {
                    ordem.setValor2(Double.parseDouble(jTextFieldValor2.getText()));
                } else {
                    // ordem.setValor2(0.0);
                }
                if (!jTextFieldValor3.getText().isEmpty()) {
                    ordem.setValor3(Double.parseDouble(jTextFieldValor3.getText()));
                } else {
                    //  ordem.setValor3(0.0);
                }
                if (!jTextFieldValor4.getText().isEmpty()) {
                    ordem.setValor4(Double.parseDouble(jTextFieldValor4.getText()));
                } else {
                    // ordem.setValor4(0.0);
                }
                valorTotal = Double.parseDouble(jTextFieldValor.getText());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Erro no campo de valor. \n Verifique se você colocou virgulas e substitua por 'Ponto'");
                return;
            }
            ordem.setValorTotal(valorTotal);
            BigDecimal a = new BigDecimal(ordem.getValorTotal());
            BigDecimal aArredondado = a.divide(BigDecimal.ONE, 2, BigDecimal.ROUND_HALF_UP);
            Extenso extenso = new Extenso(aArredondado);

            ordem.setValorPorExtenso(extenso.toString().toUpperCase());

            Pessoa clienteAlvo = (Pessoa) jComboBoxCliente.getSelectedItem();

            Endereco endereco = new Endereco();
            endereco.setBairro(jTextFieldBairro.getText());
            endereco.setLogradouro(jTextFieldEndereco.getText());
            endereco.setCep(jFormattedTextFieldCep.getText());
            endereco.setCidade(jComboBoxCidade.getSelectedItem().toString());
            endereco.setComplemento(jTextFieldComplemento.getText());
            endereco.setNumero(Integer.parseInt(jFormattedTextFieldNumero.getText()));
            endereco.setTipoLogradouro(jComboBoxTipoLogradouro.getSelectedItem().toString());
            endereco.setTelefone1(clienteAlvo.getEndereco().getTelefone1());

            ordem.setEndereco(endereco);
            TransactionManager.beginTransaction();
            new DaoOrdemServico().persistir(ordem);
            TransactionManager.commit();
            novo();
            JOptionPane.showMessageDialog(rootPane, "Registro salvo com sucesso !");
             ReportManage report = new ReportManage();
            try {
                report.relatorioPronto("reportOS", "Ordem de serviço");
            } catch (JRException ex) {
                Logger.getLogger(JDialogCadastroOrdem.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(JDialogCadastroOrdem.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(rootPane, "Contem campo(s) vazio ou tipo incorreto de dado !");
        }
    }

    private boolean validaCamposEmBranco() {

        int flag = 0;
        Color color = new Color(252, 196, 196);

        if (jTextFieldDataCadastro.getText().isEmpty()) {
            jTextFieldDataCadastro.setBackground(color);
            flag = 1;
        } else {
            jTextFieldDataCadastro.setBackground(Color.white);
        }

        if ("  /  /    ".equals(jFormattedTextFieldDataVencimento.getText())) {
            jFormattedTextFieldDataVencimento.setBackground(color);
            flag = 1;
        } else {
            jFormattedTextFieldDataVencimento.setBackground(Color.white);
        }

        if (jTextFieldValor1.getText().isEmpty()) {
            jTextFieldValor1.setBackground(color);
            flag = 1;
        } else {
            jTextFieldValor1.setBackground(Color.white);
        }

        if (jTextFieldEndereco.getText().isEmpty()) {
            jTextFieldEndereco.setBackground(color);
            flag = 1;
        } else {
            jTextFieldEndereco.setBackground(Color.white);
        }

        if (jFormattedTextFieldNumero.getText().isEmpty()) {
            jFormattedTextFieldNumero.setBackground(color);
            flag = 1;
        } else {
            jFormattedTextFieldNumero.setBackground(Color.white);
        }

        if ("     -   ".equals(jFormattedTextFieldCep.getText())) {
            jFormattedTextFieldCep.setBackground(color);
            flag = 1;
        } else {
            jFormattedTextFieldCep.setBackground(Color.white);
        }

        if (jTextFieldBairro.getText().isEmpty()) {
            jTextFieldBairro.setBackground(color);
            flag = 1;
        } else {
            jTextFieldBairro.setBackground(Color.white);
        }

        if (jTextFieldItem1.getText().isEmpty()) {
            jTextFieldItem1.setBackground(color);
            flag = 1;
        } else {
            jTextFieldItem1.setBackground(Color.white);
        }

        if (flag == 1) {
            return false;
        }
        return true;
    }

    private void preencherEndereco() {
        Pessoa clienteAlvo = (Pessoa) jComboBoxCliente.getSelectedItem();
        Endereco endereco = clienteAlvo.getEndereco();
        jComboBoxTipoLogradouro.setSelectedItem(endereco.getTipoLogradouro());
        jTextFieldEndereco.setText(endereco.getLogradouro());
        jFormattedTextFieldNumero.setText(String.valueOf(endereco.getNumero()));
        jTextFieldComplemento.setText(endereco.getComplemento());
        jFormattedTextFieldCep.setText(endereco.getCep());
        jTextFieldBairro.setText(endereco.getBairro());
        jComboBoxCidade.setSelectedItem(endereco.getCidade());
    }

    private void modificarEndereco() {
        if (jCheckBoxEndereco.isSelected()) {
            jTextFieldEndereco.setEditable(false);
            jComboBoxTipoLogradouro.setEnabled(false);
            jFormattedTextFieldNumero.setEditable(false);
            jTextFieldComplemento.setEditable(false);
            jFormattedTextFieldCep.setEditable(false);
            jTextFieldBairro.setEditable(false);
            jComboBoxCidade.setEnabled(false);
            preencherEndereco();
        } else {
            jTextFieldEndereco.setEditable(true);
            jTextFieldEndereco.setText(null);
            jComboBoxTipoLogradouro.setEnabled(true);
            jFormattedTextFieldNumero.setEditable(true);
            jFormattedTextFieldNumero.setText(null);
            jTextFieldComplemento.setEditable(true);
            jTextFieldComplemento.setText(null);
            jFormattedTextFieldCep.setEditable(true);
            jFormattedTextFieldCep.setText(null);
            jTextFieldBairro.setEditable(true);
            jTextFieldBairro.setText(null);
            jComboBoxCidade.setEnabled(true);
            jComboBoxTipoLogradouro.setSelectedIndex(0);
            jComboBoxCliente.setSelectedItem("Ubiratã");
        }
    }

    private void iniciarPreencher() {
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    if (!jTextFieldValor.getText().isEmpty()) {
                        try {
                            double valor = Double.parseDouble(jTextFieldValor.getText());
                            double parcelas = Double.parseDouble(jComboBoxQuantParcelas.getSelectedItem().toString());

                            BigDecimal a = new BigDecimal(calcularParc(valor, parcelas));
                            BigDecimal aArredondado = a.divide(BigDecimal.ONE, 2, BigDecimal.ROUND_HALF_UP);

                            jFormattedTextFieldValorPar.setText(String.valueOf(aArredondado));
                        } catch (Exception e) {
                            jFormattedTextFieldValorPar.setText("0");
                        }
                    } else {
                        jFormattedTextFieldValorPar.setText("0");
                    }
                    try {
                        sleep(1000);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
            }
        }.start();
    }

    private double calcularParc(double valor, double parcelas) {
        return valor / parcelas;
    }

    private Double calculcarValorTotal(OrdemServico ordem) {
        return ordem.getValor1() + ordem.getValor2() + ordem.getValor3() + ordem.getValor4() + ordem.getDeslocamento();
    }

    private void iniciarThreadCalculoValor() {
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    calcularValorTotal();
                    try {
                        sleep(2000);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
            }
        }.start();
    }

    private void calcularValorTotal() {
        double valor1 = 0.0;
        double valor2 = 0.0;
        double valor3 = 0.0;
        double valor4 = 0.0;
        double valorDeslocamento = 0.0;
        double total = 0.0;
        try {
            valor1 = Double.parseDouble(jTextFieldValor1.getText());
        } catch (Exception e) {
            valor1 = 0.0;
        }
        try {
            valor2 = Double.parseDouble(jTextFieldValor2.getText());
        } catch (Exception e) {
            valor2 = 0.0;
        }
        try {
            valor3 = Double.parseDouble(jTextFieldValor3.getText());
        } catch (Exception e) {
            valor3 = 0.0;
        }
        try {
            valor4 = Double.parseDouble(jTextFieldValor4.getText());
        } catch (Exception e) {
            valor4 = 0.0;
        }

        try {
            valorDeslocamento = Double.parseDouble(jTextFieldDeslocamento.getText());
        } catch (Exception e) {
            valorDeslocamento = 0.0;
        }

        total = valor1 + valor2 + valor3 + valor4 + valorDeslocamento;
        jTextFieldValor.setText(String.valueOf(total));
    }

    private int contarCaracteres(JTextField campoDeTexto) {
        return campoDeTexto.getText().length();
    }

    private void atualizarNumeroDecaracteresItem1() {
        int qtdeCaracteres = contarCaracteres(jTextFieldItem1);
        if (qtdeCaracteres > 120) {
            jLabelItem1.setText(String.valueOf(qtdeCaracteres));
            jLabelItem1.setForeground(Color.red);
            jTextFieldItem1.setBackground(new Color(252, 196, 196));
        } else {
            jLabelItem1.setText(String.valueOf(qtdeCaracteres));
            jLabelItem1.setForeground(new Color(7, 129, 17));
            jTextFieldItem1.setBackground(Color.WHITE);
        }
    }

    private void atualizarNumeroDecaracteresItem2() {
        int qtdeCaracteres = contarCaracteres(jTextFieldItem2);
        if (qtdeCaracteres > 120) {
            jLabelItem2.setText(String.valueOf(qtdeCaracteres));
            jLabelItem2.setForeground(Color.red);
            jTextFieldItem2.setBackground(new Color(252, 196, 196));
        } else {
            jLabelItem2.setText(String.valueOf(qtdeCaracteres));
            jLabelItem2.setForeground(new Color(7, 129, 17));
            jTextFieldItem2.setBackground(Color.WHITE);
        }
    }

    private void atualizarNumeroDecaracteresItem3() {
        int qtdeCaracteres = contarCaracteres(jTextFieldItem3);
        if (qtdeCaracteres > 120) {
            jLabelItem3.setText(String.valueOf(qtdeCaracteres));
            jLabelItem3.setForeground(Color.red);
            jTextFieldItem3.setBackground(new Color(252, 196, 196));
        } else {
            jLabelItem3.setText(String.valueOf(qtdeCaracteres));
            jLabelItem3.setForeground(new Color(7, 129, 17));
            jTextFieldItem3.setBackground(Color.WHITE);
        }
    }

    private void atualizarNumeroDecaracteresItem4() {
        int qtdeCaracteres = contarCaracteres(jTextFieldItem4);
        if (qtdeCaracteres > 120) {
            jLabelItem4.setText(String.valueOf(qtdeCaracteres));
            jLabelItem4.setForeground(Color.red);
            jTextFieldItem4.setBackground(new Color(252, 196, 196));
        } else {
            jLabelItem4.setText(String.valueOf(qtdeCaracteres));
            jLabelItem4.setForeground(new Color(7, 129, 17));
            jTextFieldItem4.setBackground(Color.WHITE);
        }
    }

    private void iniciarThreadQtdeCarateres() {
        new Thread() {
            @Override
            public void run() {
                while (true) {
                    atualizarNumeroDecaracteresItem1();
                    atualizarNumeroDecaracteresItem2();
                    atualizarNumeroDecaracteresItem3();
                    atualizarNumeroDecaracteresItem4();
                    try {
                        sleep(300);
                    } catch (Exception e) {
                        System.out.println(e);
                    }
                }
            }
        }.start();
    }

    private boolean verificarQtdeDeCaracteresItens() {
        if (jTextFieldItem1.getText().length() > 120 || jTextFieldItem2.getText().length() > 120 || jTextFieldItem3.getText().length() > 120 || jTextFieldItem4.getText().length() > 120) {
            JOptionPane.showMessageDialog(rootPane, "Item(ns) com número de caracteres maior que o permitido! (max. 120 caracteres)");
            return false;
        } else {
            return true;
        }
    }
}
