/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.okaynet.andare.gui;

import br.com.okaynet.andare.bibliotecas.Util;
import br.com.okaynet.andare.conexao.Data;
import br.com.okaynet.andare.conexao.TransactionManager;
import br.com.okaynet.andare.daos.DaoClienteFisico;
import br.com.okaynet.andare.daos.DaoClienteJuridico;
import br.com.okaynet.andare.daos.DaoOrdemServico;
import br.com.okaynet.andare.model.ClienteFisico;
import br.com.okaynet.andare.model.ClienteJuridico;
import br.com.okaynet.andare.model.OrdemServico;
import br.com.okaynet.andare.model.Usuarios;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Erick
 */
public class JDialogPesquisaCliente extends javax.swing.JDialog {

    /**
     * Creates new form JDialogPesquisaCliente
     */
    private DefaultTableModel model;
    private String styleModelClienteJuridico[] = new String[]{"Razão Social", "CNPJ", "Responsavel", "Insc. Estadual"};
    private String styleModelClienteFisico[] = new String[]{"Nome", "RG", "CPF"};
    private List<ClienteFisico> clientesFisicos;
    private List<ClienteJuridico> clientesJuridicos;

    public JDialogPesquisaCliente(java.awt.Frame parent, boolean modal, String chamada) {
        super(parent, modal);
        initComponents();
        if (chamada == null) {
            jRadioButtonJuridico.doClick();
        } else if (chamada.equals("F")) {
            jRadioButtonFisico.doClick();
        } else {
            jRadioButtonJuridico.doClick();
        }
        popularTabela();
        Usuarios autenticado = (Usuarios) Data.hash.get("usuario");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCliente = new javax.swing.JTable();
        jTextFieldRazao = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldInsc = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldResponsavel = new javax.swing.JTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldRg = new javax.swing.JTextField();
        jRadioButtonJuridico = new javax.swing.JRadioButton();
        jRadioButtonFisico = new javax.swing.JRadioButton();
        jFormattedTextFieldCnpj = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pesquisa de Clientes Juridico");
        setMinimumSize(new java.awt.Dimension(639, 505));
        setPreferredSize(new java.awt.Dimension(639, 505));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Razão Social", "CNPJ", "Responsavel", "Insc. Estadual"
            }
        ));
        jScrollPane1.setViewportView(jTableCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 590, 270));

        jTextFieldRazao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRazaoKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldRazao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 140, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel12.setText("Razão Social:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jTextFieldInsc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldInscKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldInsc, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 110, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel13.setText("CNPJ:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel14.setText("Responsavel:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel15.setText("Insc. Estadual:");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 20, -1, -1));

        jTextFieldResponsavel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldResponsavelKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldResponsavel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 120, -1));

        jTextFieldNome.setEditable(false);
        jTextFieldNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldNomeKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setText("Nome:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel17.setText("RG:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel18.setText("CPF:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, -1, -1));

        jTextFieldRg.setEditable(false);
        jTextFieldRg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldRgKeyReleased(evt);
            }
        });
        getContentPane().add(jTextFieldRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 140, -1));

        buttonGroup1.add(jRadioButtonJuridico);
        jRadioButtonJuridico.setText("Juridico");
        jRadioButtonJuridico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonJuridicoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonJuridico, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, -1, -1));

        buttonGroup1.add(jRadioButtonFisico);
        jRadioButtonFisico.setSelected(true);
        jRadioButtonFisico.setText("Físico");
        jRadioButtonFisico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFisicoActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, -1, -1));

        try {
            jFormattedTextFieldCnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldCnpj, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 140, -1));

        jFormattedTextFieldCpf.setEditable(false);
        try {
            jFormattedTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextFieldCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 120, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/okaynet/andare/icons/1372094443_Magnifier2.png"))); // NOI18N
        jButton9.setBorderPainted(false);
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 30, 30));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/okaynet/andare/icons/1372094443_Magnifier2.png"))); // NOI18N
        jButton10.setBorderPainted(false);
        jButton10.setFocusPainted(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 30, 30));

        jMenuBar1.setMinimumSize(new java.awt.Dimension(56, 31));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(396, 31));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/okaynet/andare/icons/png/108.png"))); // NOI18N
        jMenu1.setText("Editar");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/okaynet/andare/icons/png/004.png"))); // NOI18N
        jMenu3.setText("Apagar");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenu3MouseEntered(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/okaynet/andare/icons/png/010.png"))); // NOI18N
        jMenu6.setText("Voltar");
        jMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu6MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/okaynet/andare/icons/png/024.png"))); // NOI18N
        jMenu7.setText("Limpar Pesquisa");
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu7MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        if (jMenu3.isSelected()) {
            if (jTableCliente.getSelectedRow() != -1) {
                if (Util.mostraMensagemEmTela("Deseja realmente excluir?")) {
                    deletar();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Nenhum registro selecionado!");
            }
        }

    }//GEN-LAST:event_jMenu3MouseClicked

    private void jRadioButtonJuridicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonJuridicoActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonJuridico.isSelected()) {
            jTextFieldRg.setEditable(false);
            jTextFieldNome.setEditable(false);
            jFormattedTextFieldCpf.setEditable(false);
            jTextFieldRazao.setEditable(true);
            jTextFieldInsc.setEditable(true);
            jTextFieldResponsavel.setEditable(true);
            jFormattedTextFieldCnpj.setEditable(true);

            jTextFieldRg.setText(null);
            jTextFieldInsc.setText(null);
            jTextFieldNome.setText(null);
            jTextFieldResponsavel.setText(null);
            jTextFieldRazao.setText(null);
            jFormattedTextFieldCnpj.setText(null);
            jFormattedTextFieldCpf.setText(null);


            popularTabela();
        }
    }//GEN-LAST:event_jRadioButtonJuridicoActionPerformed

    private void jRadioButtonFisicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFisicoActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonFisico.isSelected()) {
            jTextFieldRg.setEditable(true);
            jTextFieldNome.setEditable(true);
            jFormattedTextFieldCpf.setEditable(true);
            jTextFieldRazao.setEditable(false);
            jTextFieldInsc.setEditable(false);
            jTextFieldResponsavel.setEditable(false);
            jFormattedTextFieldCnpj.setEditable(false);

            jTextFieldRg.setText(null);
            jTextFieldInsc.setText(null);
            jTextFieldNome.setText(null);
            jTextFieldResponsavel.setText(null);
            jTextFieldRazao.setText(null);
            jFormattedTextFieldCnpj.setText(null);
            jFormattedTextFieldCpf.setText(null);

            popularTabela();
        }
    }//GEN-LAST:event_jRadioButtonFisicoActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        if (jMenu1.isSelected()) {
            if (jTableCliente.getSelectedRow() != -1) {


                if (jRadioButtonFisico.isSelected()) {
                    Data.hash.put("clienteFisico", clientesFisicos.get(jTableCliente.getSelectedRow()));
                } else {
                    Data.hash.put("clienteJuridico", clientesJuridicos.get(jTableCliente.getSelectedRow()));
                }


                if (jRadioButtonJuridico.isSelected()) {
                    Util.abrirDialogCentralizado(new JDialogCadastroClienteJuridicoPopUp(null, true));
                } else {
                    Util.abrirDialogCentralizado(new JDialogCadastroClienteFisicoPopUp(null, true));
                }
                popularTabela();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Nenhum registro selecionado!");
            }
        }
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu6MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Util.abrirDialogCentralizado(new JDialogCadastroClienteFisico(null, true));
        this.dispose();
    }//GEN-LAST:event_jMenu6MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jTextFieldRg.setText(null);
        jTextFieldInsc.setText(null);
        jTextFieldResponsavel.setText(null);
        jTextFieldRazao.setText(null);
        jFormattedTextFieldCpf.setText(null);
        jTextFieldRg.setText(null);
        obterPorCnpj();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jTextFieldRg.setText(null);
        jTextFieldInsc.setText(null);
        jTextFieldResponsavel.setText(null);
        jTextFieldRazao.setText(null);
        jFormattedTextFieldCnpj.setText(null);
        jTextFieldRg.setText(null);
        obterPorCpf();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jTextFieldNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNomeKeyReleased
        // TODO add your handling code here:

        jTextFieldRg.setText(null);
        jTextFieldInsc.setText(null);
        jTextFieldResponsavel.setText(null);
        jTextFieldRazao.setText(null);
        jFormattedTextFieldCnpj.setText(null);
        jFormattedTextFieldCpf.setText(null);
        obterPorNome();

    }//GEN-LAST:event_jTextFieldNomeKeyReleased

    private void jTextFieldRgKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRgKeyReleased
        // TODO add your handling code here:

        jTextFieldInsc.setText(null);
        jTextFieldResponsavel.setText(null);
        jTextFieldRazao.setText(null);
        jFormattedTextFieldCnpj.setText(null);
        jFormattedTextFieldCpf.setText(null);
        jTextFieldNome.setText(null);
        obterPorRg();

    }//GEN-LAST:event_jTextFieldRgKeyReleased

    private void jTextFieldRazaoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldRazaoKeyReleased
        // TODO add your handling code here:

        jTextFieldRg.setText(null);
        jTextFieldInsc.setText(null);
        jTextFieldResponsavel.setText(null);
        jTextFieldNome.setText(null);
        jFormattedTextFieldCnpj.setText(null);
        jFormattedTextFieldCpf.setText(null);
        obterPorRazao();
    }//GEN-LAST:event_jTextFieldRazaoKeyReleased

    private void jTextFieldResponsavelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldResponsavelKeyReleased
        // TODO add your handling code here:
        jTextFieldRg.setText(null);
        jTextFieldInsc.setText(null);
        jTextFieldRazao.setText(null);
        jTextFieldNome.setText(null);
        jFormattedTextFieldCnpj.setText(null);
        jFormattedTextFieldCpf.setText(null);

        obterPorResponsavel();
    }//GEN-LAST:event_jTextFieldResponsavelKeyReleased

    private void jTextFieldInscKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldInscKeyReleased
        // TODO add your handling code here:
        jTextFieldRg.setText(null);
        jTextFieldResponsavel.setText(null);
        jTextFieldRazao.setText(null);
        jTextFieldNome.setText(null);
        jFormattedTextFieldCnpj.setText(null);
        jFormattedTextFieldCpf.setText(null);

        obterPorInsc();
    }//GEN-LAST:event_jTextFieldInscKeyReleased

    private void jMenu3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3MouseEntered

    private void jMenu7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MouseClicked
        // TODO add your handling code here:
        popularTabela();
        jFormattedTextFieldCpf.setText(null);
        jFormattedTextFieldCnpj.setText(null);
        jTextFieldInsc.setText(null);
        jTextFieldNome.setText(null);
        jTextFieldRazao.setText(null);
        jTextFieldResponsavel.setText(null);
        jTextFieldRg.setText(null);
    }//GEN-LAST:event_jMenu7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogPesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogPesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogPesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogPesquisaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogPesquisaCliente dialog = new JDialogPesquisaCliente(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JFormattedTextField jFormattedTextFieldCnpj;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButtonFisico;
    private javax.swing.JRadioButton jRadioButtonJuridico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableCliente;
    private javax.swing.JTextField jTextFieldInsc;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldRazao;
    private javax.swing.JTextField jTextFieldResponsavel;
    private javax.swing.JTextField jTextFieldRg;
    // End of variables declaration//GEN-END:variables

    private void popularTabelaFisico() {
        if (jRadioButtonFisico.isSelected()) {
            TransactionManager.beginTransaction();
            clientesFisicos = new DaoClienteFisico().listar("", "nome");
            TransactionManager.commit();

            prencherPessoasTabelaFisica();
        }
    }

    private void popularTabelaJuridico() {
        if (jRadioButtonJuridico.isSelected()) {
            TransactionManager.beginTransaction();
            clientesJuridicos = new DaoClienteJuridico().listar("", "razaoSocial");
            TransactionManager.commit();

            prencherPessoasTabelaJuridica();
        }
    }

    private void prencherPessoasTabelaFisica() {
        if (jRadioButtonFisico.isSelected()) {
            if (clientesFisicos != null && !clientesFisicos.isEmpty()) {
                model = new DefaultTableModel();
                model.setColumnIdentifiers(styleModelClienteFisico);
                for (ClienteFisico cliente : clientesFisicos) {
                    model.addRow(new Object[]{cliente.getNome(), cliente.getRg(), cliente.getCpf()});
                }
                jTableCliente.setModel(model);
            } else {
                model = new DefaultTableModel();
                model.setColumnIdentifiers(styleModelClienteFisico);
                jTableCliente.setModel(model);
            }
        }
    }

    private void prencherPessoasTabelaJuridica() {
        if (jRadioButtonJuridico.isSelected()) {
            if (clientesJuridicos != null && !clientesJuridicos.isEmpty()) {
                model = new DefaultTableModel();
                model.setColumnIdentifiers(styleModelClienteJuridico);
                for (ClienteJuridico cliente : clientesJuridicos) {
                    model.addRow(new Object[]{cliente.getRazaoSocial(), cliente.getCnpj(), cliente.getResponsavel(), cliente.getInscricao()});
                }
                jTableCliente.setModel(model);
            } else {
                model = new DefaultTableModel();
                model.setColumnIdentifiers(styleModelClienteJuridico);
                jTableCliente.setModel(model);
            }
        }
    }

    private void deletar() {
        if (jRadioButtonFisico.isSelected()) {
            TransactionManager.beginTransaction();

            List<OrdemServico> obterClienteID = new DaoOrdemServico().obterClientesID(clientesFisicos.get(jTableCliente.getSelectedRow()).getId());
            if (obterClienteID.isEmpty()) {

                new DaoClienteFisico().remover(clientesFisicos.get(jTableCliente.getSelectedRow()));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Este cliente possui OS vinculadas a ele.");
            }
            TransactionManager.commit();
            popularTabelaFisico();
        } else if (jRadioButtonJuridico.isSelected()) {
            TransactionManager.beginTransaction();
            List<OrdemServico> obterClienteID = new DaoOrdemServico().obterClientesID(clientesJuridicos.get(jTableCliente.getSelectedRow()).getId());
            if (obterClienteID.isEmpty()) {

                new DaoClienteJuridico().remover(clientesJuridicos.get(jTableCliente.getSelectedRow()));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Este cliente possui OS vinculadas a ele.");
            }
            TransactionManager.commit();
            popularTabelaJuridico();
        }
    }

    private void popularTabela() {
        if (jRadioButtonFisico.isSelected()) {
            popularTabelaFisico();
        } else {
            popularTabelaJuridico();
        }
    }

    private void obterPorNome() {
        TransactionManager.beginTransaction();
        clientesFisicos = new DaoClienteFisico().obterNome(jTextFieldNome.getText());
        TransactionManager.commit();
        prencherPessoasTabelaFisica();
    }

    private void obterPorRg() {
        TransactionManager.beginTransaction();
        clientesFisicos = new DaoClienteFisico().obterRg(jTextFieldRg.getText());
        TransactionManager.commit();
        prencherPessoasTabelaFisica();
    }

    private void obterPorCpf() {
        TransactionManager.beginTransaction();
        clientesFisicos = new DaoClienteFisico().obterCpf(jFormattedTextFieldCpf.getText());
        TransactionManager.commit();
        prencherPessoasTabelaFisica();
    }

    private void obterPorRazao() {
        TransactionManager.beginTransaction();
        clientesJuridicos = new DaoClienteJuridico().obterRazao(jTextFieldRazao.getText());
        TransactionManager.commit();
        prencherPessoasTabelaJuridica();
    }

    private void obterPorCnpj() {
        TransactionManager.beginTransaction();
        clientesJuridicos = new DaoClienteJuridico().obterCnpj(jFormattedTextFieldCnpj.getText());
        TransactionManager.commit();
        prencherPessoasTabelaJuridica();
    }

    private void obterPorResponsavel() {
        TransactionManager.beginTransaction();
        clientesJuridicos = new DaoClienteJuridico().obterResponsavel(jTextFieldResponsavel.getText());
        TransactionManager.commit();
        prencherPessoasTabelaJuridica();
    }

    private void obterPorInsc() {
        TransactionManager.beginTransaction();
        clientesJuridicos = new DaoClienteJuridico().obterInsc(jTextFieldInsc.getText());
        TransactionManager.commit();
        prencherPessoasTabelaJuridica();
    }
}
