package br.com.okaynet.andare.gui;

import br.com.okaynet.andare.bibliotecas.Util;
import br.com.okaynet.andare.conexao.Conexao;
import br.com.okaynet.andare.conexao.Data;
import br.com.okaynet.andare.conexao.HibernateConfiguration;
import br.com.okaynet.andare.daos.DaoUsuarios;
import br.com.okaynet.andare.model.Usuarios;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Erick
 */
public class JFrameLogin extends javax.swing.JFrame {

    /**
     * Creates new form JFrameLogin
     */
    public JFrameLogin() {
        initComponents();
    


        mudarFavicon();
        jTextUser.setBackground(new Color(58, 96, 99));
        jPassword.setBackground(new Color(58, 96, 99));

        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception ex) {
            System.out.println(ex);
        }

        try {
            if (!jHost.getText().isEmpty()) {
                HibernateConfiguration.setBase("okaynet");
                HibernateConfiguration.setHost(jHost.getText()+":3306");
                HibernateConfiguration.setPass("okaynet1618");
                HibernateConfiguration.setUser("root");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Host Inválido!");
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Host Inválido!");
            return;
        }

        try {

            Connection conexao = Conexao.getConnection();
            conexao.createStatement().execute("create database if not EXISTS " + HibernateConfiguration.getBase());
            conexao.createStatement().execute("use " + HibernateConfiguration.getBase());

            ResultSet execute = conexao.createStatement().executeQuery("show tables");

            if (!execute.next()) {

                Util.abrirDialogCentralizado(new JDialogCriacaoBase(this, true, null));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Aconteceu erro inesperado, entre em contato com seu desenvolvedor Okaynet");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Aconteceu erro inesperado, entre em contato com seu desenvolvedor Okaynet");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextUser = new javax.swing.JTextField();
        jHost = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Sistema = new javax.swing.JMenu();
        Entrar = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Okaynet Informática - OS Manager");
        setMaximumSize(new java.awt.Dimension(542, 263));
        setMinimumSize(new java.awt.Dimension(542, 263));
        setPreferredSize(new java.awt.Dimension(542, 263));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextUser.setBackground(new java.awt.Color(204, 204, 204));
        jTextUser.setForeground(new java.awt.Color(51, 51, 51));
        jTextUser.setToolTipText("");
        jTextUser.setBorder(null);
        jTextUser.setCaretColor(new java.awt.Color(153, 153, 153));
        jTextUser.setOpaque(false);
        getContentPane().add(jTextUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 200, 20));

        jHost.setEditable(false);
        jHost.setBackground(new java.awt.Color(204, 204, 204));
        jHost.setForeground(new java.awt.Color(51, 51, 51));
        jHost.setText("127.0.0.1");
        jHost.setToolTipText("");
        jHost.setBorder(null);
        jHost.setCaretColor(new java.awt.Color(153, 153, 153));
        jHost.setOpaque(false);
        jHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHostActionPerformed(evt);
            }
        });
        getContentPane().add(jHost, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 200, 20));

        jPassword.setBackground(new java.awt.Color(204, 204, 204));
        jPassword.setForeground(new java.awt.Color(51, 51, 51));
        jPassword.setBorder(null);
        jPassword.setCaretColor(new java.awt.Color(153, 153, 153));
        jPassword.setOpaque(false);
        getContentPane().add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 200, 20));

        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 120, 30));

        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/okaynet/andare/icons/login.jpg"))); // NOI18N
        jLabelLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 540, 250));

        jMenuBar1.setMaximumSize(new java.awt.Dimension(1, 1));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(1, 1));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(1, 1));

        Sistema.setText("Sistema");

        Entrar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0));
        Entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/okaynet/andare/icons/png/047.png"))); // NOI18N
        Entrar.setText("Fazer Login");
        Entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarActionPerformed(evt);
            }
        });
        Sistema.add(Entrar);

        Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/okaynet/andare/icons/png/048.png"))); // NOI18N
        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Sistema.add(Sair);

        jMenuBar1.add(Sistema);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleDescription("Login");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:

        verificarLogin(jTextUser.getText(), jPassword.getText());
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jHostActionPerformed

    private void EntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarActionPerformed
        // TODO add your handling code here:
        verificarLogin(jTextUser.getText(), jPassword.getText());
    }//GEN-LAST:event_EntrarActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Entrar;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JMenu Sistema;
    private javax.swing.JTextField jHost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jTextUser;
    // End of variables declaration//GEN-END:variables

    private void mudarFavicon() {
        URL url = this.getClass().getResource("/br/com/okaynet/andare/icons/faststone.png");
        Image imagemTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(imagemTitulo);
    }

    private void verificarLogin(String usuario, String senha) {

        Usuarios autenticado = new DaoUsuarios().autenticarUsuario(usuario, Util.md5(senha));
        if (autenticado != null) {
            Data.hash.put("usuario", autenticado);
            Util.abrirDialogCentralizadoForm(new JFramePrincipal());
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Usuário ou senha inválidos!");
        }

    }
}
